version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    networks:
      - act_11
    volumes:
      - mongo_datav12:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
      - MONGO_INITDB_DATABASE=cruddb

  app:
    build: .
    container_name: node_appv11
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - act_11
    environment:
      - MONGO_HOST=mongodb  #    
      - MONGO_PORT=27017
      - MONGO_DB=cruddb
      - MONGO_USER=myuser
      - MONGO_PASS=mypassword

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8089:8081"
    networks:
      - act_11
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=myuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mypassword
      - ME_CONFIG_MONGODB_SERVER=mongodb  # Service name of MongoDB
      - ME_CONFIG_BASICAUTH_USERNAME=admin  # Optional: Username for accessing Mongo Express
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  # Optional: Password for accessing Mongo Express

 #     ME_CONFIG_MONGODB_SERVER: mongodb
 #     ME_CONFIG_MONGODB_PORT: 27017
 #     ME_CONFIG_BASICAUTH_USERNAME: admin
 #     ME_CONFIG_BASICAUTH_PASSWORD: password


networks:
  act_11:



volumes:
  mongo_datav12:
