apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: raemondarellano/mongo-app:latest
        ports:
        - containerPort: 27017
        env:

        - name: MONGO_INITDB_ROOT_USERNAME       #USERNAME IN MONGO
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_USER

        - name: MONGO_INITDB_ROOT_PASSWORD          #PASSWORD IN MONGO
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_PASS

        - name: MONGO_INITDB_DATABASE              # MONGO DATABASE NAME
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: MONGO_DB


        volumeMounts:                              # VOLUME FOR DATABASE
          - name: mongodb-storage
            mountPath: /data/db
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
